---

# A simple Pulsar 'sanity check'.

- name: Run Pulsar check
  command: "./exec.sh {{ cmd }}"
  vars:
    cmd: >-
      pulsar-check
      --private_token '{{ pulsar_token }}'
      --url='http://localhost:8443'
  args:
    chdir: "{{ venv_path }}"
  changed_when: false
  register: pulsar_check
  ignore_errors: yes
  become: yes
  become_user: pulsar

- name: Display Pulsar output
  debug:
    var: pulsar_check
  when: pulsar_check.rc

- name: Assert Pulsar success
  assert:
    that: pulsar_check.rc == 0
