---

# A simple Pulsar 'sanity check'.

- name: Run Pulsar check
  command: "./exec.sh {{ cmd }}"
  vars:
    cmd: >-
      pulsar-check
      --private_token '{{ pulsar_token }}'
      --url='http://localhost:8443'
  args:
    chdir: "{{ venv_path }}"
  changed_when: false
  register: pulsar_check
  ignore_errors: yes
  async: 45
  poll: 5
  become: yes
  become_user: pulsar

- name: Display Pulsar output
  debug:
    var: pulsar_check.stderr_lines[-1]
  when:
  - pulsar_check.rc
  - pulsar_check.stderr_lines|length > 0

- name: Assert Pulsar success
  assert:
    that: pulsar_check.rc == 0
