---

- name: Create Pulsar group
  group:
    name: pulsar
    gid: "{{ pulsar_uid }}"
    state: present

- name: Create Pulsar user
  user:
    name: pulsar
    group: pulsar
    groups: wheel
    uid: "{{ pulsar_uid }}"
    home: "{{ volume_mount }}/pulsar"

- name: Add password-less sudo privilege to Pulsar user
  copy:
    content: "pulsar ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/pulsar
