---

- name: Assert Ansible version
  assert:
    that: ansible_version.full is version('2.8', '>=')

- name: Check slurm/munge installation combination
  fail:
    msg: If you install slurm you must install MUNGE
  when:
  - install_slurm|bool and not install_munge|bool

# Before we continue,
# make sure the user actually wants to create the cloud...

- name: Assert key variables
  assert:
    that:
    - worker_count > 0

- name: Create Cloud?
  pause:
    prompt: |-
      Are you sure you want to create the '{{ instance_base_name }}' cloud?
      Hit return to create.
      Hit Ctrl+c and then "a" if you've changed your mind

# Off we go...

- include_tasks: create-{{ provider }}-instances.yaml
- include_tasks: gather-{{ provider }}-facts.yaml
