---

dist: xenial
language: python
python:
- 3.7
install:
- pip install -r requirements.txt
- pip install -r build-requirements.txt
script:
- ansible-lint site.yaml unsite.yaml
- yamllint site.yaml unsite.yaml inventory.yaml
- yamllint group_vars roles
- yamllint .travis.yml
