---

# Runs a series of sanity-checks on the cluster,
# based on what components are installed.

- hosts: localhost
  tasks:
  - include_role:
      name: cloud
      tasks_from: gather-openstack-facts.yaml

- hosts: head
  become: yes
  tasks:
  - include_role:
      name: app-slurm
      tasks_from: check-sinfo.yaml
    when: install_slurm|bool
