---

# Runs a series of sanity-checks on the cluster,
# based on what components are installed.

- name: Assert Ansible version
  assert:
    that: ansible_version.full is version('2.8', '>=')

- name: Assert key variables
  assert:
    that:
    - os_auth_url is defined
    - os_auth_url|length > 0

- hosts: localhost
  tasks:
  - include_role:
      name: cloud
      tasks_from: gather-openstack-facts.yaml

- hosts: head
  become: yes
  tasks:
  - include_role:
      name: app-slurm
      tasks_from: check-sinfo.yaml
    when: install_slurm|bool
