---

# A simple Slurm 'sanity check'.
# This verifies 'sinfo' returns the right number of 'responding' nodes.

- name: Get node summary
  shell: sinfo -hs | tr -s ' ' | cut -d' ' -f 4  # noqa 305
  register: sinfo_summary
  changed_when: false

- name: Set node count facts
  set_fact:
    active_num: "{{ sinfo_summary.stdout.split('/')[0] }}"
    idle_num: "{{ sinfo_summary.stdout.split('/')[1] }}"
    offline_num: "{{ sinfo_summary.stdout.split('/')[2] }}"
    total_num: "{{ sinfo_summary.stdout.split('/')[3] }}"

- name: Display node summary
  debug:
    msg: A={{ active_num }} I={{ idle_num }} O={{ offline_num }} T={{ total_num }}

- name: Check offline and total node count
  assert:
    that:
    - offline_num|int == 0
    - total_num|int == worker_count
