---

# A simple Slurm 'sanity check'.
# This verifies 'sinfo' returns the right number of 'responding' nodes.

- name: Get node summary
  shell: sinfo -hs | tr -s ' ' | cut -d' ' -f 4  # noqa 305 306 501
  register: sinfo_summary
  changed_when: false

- name: Set node count facts
  set_fact:
    active_num: "{{ sinfo_summary.stdout.split('/')[0] }}"
    idle_num: "{{ sinfo_summary.stdout.split('/')[1] }}"
    offline_num: "{{ sinfo_summary.stdout.split('/')[2] }}"
    total_num: "{{ sinfo_summary.stdout.split('/')[3] }}"

- name: Set online facts
  set_fact:
    online_num: "{{ total_num|int - offline_num|int }}"

- name: Display node summary
  debug:
    msg: A={{ active_num }} I={{ idle_num }} O={{ offline_num }} T={{ total_num }}

- name: Check total node count
  assert:
    that: total_num|int == worker_count
    success_msg: All nodes are known to Slurm

- name: Check at least some online
  assert:
    that: online_num|int > 0
    fail_msg: Every node appears to be offline!
    success_msg: "{{ online_num }} nodes are online"
