---
name: lint

on:
- push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - 3.8

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
        pip install -r requirements.txt
        ansible-galaxy install -r requirements.yml
    - name: Lint
      run: |
        yamllint site.yaml unsite.yaml inventory.yaml
        yamllint group_vars roles
        ansible-lint site.yaml unsite.yaml
